### ISSUE TITLE
Ground Truth Matching GIS Errors

### ISSUE THREAD

**Issue by b-i-l-l-c-a-o** [e-mission/e-mission-server#612]
While attempting to run the new GIS ground truth matching fork, we ran into two errors. One of which did not stop the script, one did. To reproduce, execute 'python bin/intake_multiprocess.py 3' from Shankari's fork on the ground_truth_matching branch with data (can/will msg data once the people whose data it belongs to is awake; don't want to make their location data public without them knowing).

First error's traceback is shown below. This one did not stop the script.
![image](https://user-images.githubusercontent.com/35613790/48476107-03941a00-e7b3-11e8-970a-82903f6614ab.png)

Second error's traceback is shown below. This one did stop the script. 
![image](https://user-images.githubusercontent.com/35613790/48475792-6a650380-e7b2-11e8-9771-f1b32763a064.png)

**Comment by shankari** [comment]
Copy-pasting from previous slack message:

1. Please include the data associated with the day so that I can try to reproduce
2. Screenshots are easy for you but hard for everybody else because they are not searchable or copy-pastable or anything. Please include errors as markdown.
3. for this particular error, have you searched the docs? @valin reported the exact same error earlier and I updated the docs (https://github.com/e-mission/e-mission-docs/blob/ab5ab9fb482c832d3367242eea2ca58adcada4e5/docs/e-mission-server/pipeline_details.md) (edited)
